import { projectsHTML, projectsJS, projectsReact } from "@/data";
import type { Metadata } from "next";
import ProjectsItem from "@/components/ProjectsItem";
import { Fragment } from "react";
import HeaderTop from "@/components/Header/HeaderTop";

export const metadata: Metadata = {
  title: "Projects - Pirnau Artemie",
  description: "Generated by create next app",
};

export default function ProjectsList() {
  return (
    <Fragment>
      <HeaderTop />
      <h2 className="text-center text-4xl uppercase font-semibold mb-10">
        Portfolio
      </h2>
      <div className="design grid grid-cols-3 gap-x-12 gap-y-2">
        {projectsHTML.map(({ id, img, link, title }) => (
          <ProjectsItem
            key={`html-${id}`}
            id={id}
            img={img}
            link={link}
            title={title}
          />
        ))}
      </div>
      <div className="js grid grid-cols-3 gap-x-12 gap-y-2">
        {projectsJS.map(({ id, img, link, title }) => (
          <ProjectsItem
            key={`js-${id}`}
            id={id}
            img={img}
            link={link}
            title={title}
          />
        ))}
      </div>
      <div className="react grid grid-cols-3 ggap-x-12 gap-y-2 mb-28">
        {projectsReact.map(({ id, img, link, title }) => (
          <ProjectsItem
            key={`react-${id}`}
            id={id}
            img={img}
            link={link}
            title={title}
          />
        ))}
      </div>
    </Fragment>
  );
}
