import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "./providers";
import "../styles/globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer";
import Loading from "./loading";
const poppins = Inter({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Pirnau Artemie - Front End Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.className} cursor-default`}>
        <Providers>
          <div className="container">
            <main className="">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
